#!/usr/bin/env python3
"""Generate one rerun+eval script per finished ILI HPO sub-experiment.

Scans ``outputs/hpo/<dataset>/<periodfolder>/<tau>/<expname>/best_run.json``
(written by ``hpo_grid_search.py``) and emits
``scripts/hpo/<dataset>_rerun/<periodfolder>/<tau>/rerun_<expname>.sh``.
``<dataset>`` is ``--dataset`` (default ``ili``; e.g. ``ili_delta``) and also
namespaces the scripts' log dir (``Logs/hpo/<dataset>_rerun``).

Each emitted script takes a GPU id as ``$1`` (default 0) and, in one detached
subshell:

  1. regenerates ``<exp_dir>/best_synth.npz`` via ``rerun_best_hpo.py`` (conda
     env ``diffusiontf``);
  2. evaluates that npz against its training npz with
     ``timeVAE/src/eval_external_synth.py`` (conda env ``timevae``), writing
     ``<exp_dir>/timevae_eval/``.

Scripts self-detach (``( ... ) &``) so the existing ``run_queue.sh`` dispatcher,
which polls GPU memory to find a free card, works unchanged. Pass the generated
``scripts/hpo/ili_rerun/manifest.txt`` to it as the 3rd argument.

Re-run this generator whenever new ``best_run.json`` files appear under
``outputs/hpo/<dataset>``.
"""
from __future__ import annotations

import argparse
import json
import stat
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]          # .../Diffusion-TS
PROJ_ROOT = REPO_ROOT.parent                             # .../Projects (holds timeVAE/)

SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# AUTO-GENERATED by scripts/hpo/gen_ili_rerun_scripts.py - do not edit by hand.
# Rerun best HPO + timeVAE eval for {expname}.  Usage: ./rerun_{expname}.sh [GPU_ID]  (default 0)
set -euo pipefail
GPU="${{1:-0}}"
REPO={repo}
PROJ={proj}
EXP="$REPO/outputs/hpo/{dataset}/{periodfolder}/{tau}/{expname}"
DATA="$REPO/{train_npz}"
mkdir -p "$REPO/Logs/hpo/{dataset}_rerun/{periodfolder}/{tau}"
TS=$(date +%F_%H-%M-%S)
LOG="$REPO/Logs/hpo/{dataset}_rerun/{periodfolder}/{tau}/{expname}_${{TS}}.log"
(
  set -euo pipefail
  source /data/jinyuli/anaconda3/etc/profile.d/conda.sh
  cd "$REPO"
  conda activate diffusiontf
  python rerun_best_hpo.py --hpo-dir "$EXP" --gpu "$GPU"
  conda activate timevae
  python "$PROJ/timeVAE/src/eval_external_synth.py" \\
    --data-npz   "$DATA" \\
    --synth-npz  "$EXP/best_synth.npz" \\
    --output-dir "$EXP/timevae_eval" \\
    --split-method tail_holdout --valid-perc 0 \\
    --compare-split train --max-tsne-samples 20000 --no-histogram
) > "$LOG" 2>&1 &
disown
echo "[launched] {expname} on GPU ${{GPU}}  pid=$!  log=$LOG"
"""


def discover(out_root: Path):
    """Yield dicts describing each sub-experiment that has a best_run.json."""
    items = []
    for bj in sorted(out_root.rglob("best_run.json")):
        exp_dir = bj.parent
        rel = exp_dir.relative_to(out_root)               # <periodfolder>/<tau>/<expname>
        if len(rel.parts) != 3:
            print(f"[skip] unexpected depth: {bj.relative_to(REPO_ROOT)}")
            continue
        periodfolder, tau, expname = rel.parts
        try:
            best = json.loads(bj.read_text())
        except json.JSONDecodeError as e:
            print(f"[skip] cannot parse {bj.relative_to(REPO_ROOT)}: {e}")
            continue
        train_npz = best.get("train_npz")
        if not train_npz:
            print(f"[warn] no train_npz in {bj.relative_to(REPO_ROOT)} -> skip")
            continue
        if not (REPO_ROOT / train_npz).exists():
            print(f"[warn] train npz missing ({train_npz}) for {expname} -> skip")
            continue
        items.append({
            "periodfolder": periodfolder,
            "tau": tau,
            "expname": expname,
            "train_npz": train_npz,
        })
    return items


def main():
    ap = argparse.ArgumentParser(description="Generate per-sub-experiment ILI rerun+eval scripts.")
    ap.add_argument("--dataset", default="ili",
                    help="Dataset tree under outputs/hpo/ to scan (e.g. ili, "
                         "ili_delta). Also namespaces Logs/hpo/<dataset>_rerun "
                         "and the default --out-dir.")
    ap.add_argument("--out-dir", default=None,
                    help="Where to write the rerun_*.sh tree "
                         "(default scripts/hpo/<dataset>_rerun).")
    ap.add_argument("--dry-run", action="store_true",
                    help="List intended scripts without writing anything.")
    args = ap.parse_args()

    out_dir = Path(args.out_dir).resolve() if args.out_dir else (
        REPO_ROOT / "scripts" / "hpo" / f"{args.dataset}_rerun"
    )
    items = discover(REPO_ROOT / "outputs" / "hpo" / args.dataset)

    manifest_lines = []
    for it in items:
        script_dir = out_dir / it["periodfolder"] / it["tau"]
        script_path = script_dir / f"rerun_{it['expname']}.sh"
        manifest_lines.append(str(script_path.relative_to(REPO_ROOT)))
        if args.dry_run:
            print(f"[dry] {script_path.relative_to(REPO_ROOT)}")
            continue
        script_dir.mkdir(parents=True, exist_ok=True)
        content = SCRIPT_TEMPLATE.format(repo=REPO_ROOT, proj=PROJ_ROOT,
                                         dataset=args.dataset, **it)
        script_path.write_text(content)
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        print(f"[write] {script_path.relative_to(REPO_ROOT)}")

    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)
        manifest = out_dir / "manifest.txt"
        manifest.write_text("\n".join(sorted(manifest_lines)) + "\n")
        print(f"[write] {manifest.relative_to(REPO_ROOT)}")

    print(f"\n{'[dry-run] would generate' if args.dry_run else 'generated'} "
          f"{len(items)} script(s).")


if __name__ == "__main__":
    main()
