#!/usr/bin/env bash
# AUTO-GENERATED by scripts/hpo/gen_ili_hpo_scripts.py - do not edit by hand.
# HPO for eng_2018_2019_tau02_p7.  Usage: ./run_eng_2018_2019_tau02_p7.sh [GPU_ID]   (default 0)
set -euo pipefail
GPU="${1:-0}"
REPO=/data/jinyuli/Projects/Diffusion-TS
cd "$REPO"
mkdir -p Logs/hpo/ili_delta/2018_19test_tau/tau02
TS=$(date +%F_%H-%M-%S)
OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 nohup python hpo_grid_search.py \
  --base-config Config/ili.yaml \
  --train-npz Data/datasets/ili_delta/2018_19test_tau/tau02/ili_eng_2018_2019_T42_p7_train.npz \
  --val-npz   Data/datasets/ili_delta/2018_19test_tau/tau02/ili_eng_2018_2019_T42_p7_val.npz \
  --d-model 64 128 \
  --base-lr 1e-5 \
  --batch-size 64 128 \
  --max-epochs 18000 --save-cycle 1800 --val-num-repeats 3 \
  --gpu-slots "${GPU}:2" \
  --experiment-name eng_2018_2019_tau02_p7 \
  --output-root outputs/hpo/ili_delta/2018_19test_tau/tau02 \
  > "Logs/hpo/ili_delta/2018_19test_tau/tau02/eng_2018_2019_tau02_p7_${TS}.log" 2>&1 &
echo "[launched] eng_2018_2019_tau02_p7 on GPU ${GPU}  pid=$!  log=Logs/hpo/ili_delta/2018_19test_tau/tau02/eng_2018_2019_tau02_p7_${TS}.log"
