#!/usr/bin/env bash
# AUTO-GENERATED by scripts/hpo/gen_ili_hpo_scripts.py - do not edit by hand.
# HPO for eng_2017_2018_tau03_p14.  Usage: ./run_eng_2017_2018_tau03_p14.sh [GPU_ID]   (default 0)
set -euo pipefail
GPU="${1:-0}"
REPO=/data/jinyuli/Projects/Diffusion-TS
cd "$REPO"
mkdir -p Logs/hpo/ili_delta/2017_18test_tau/tau03
TS=$(date +%F_%H-%M-%S)
OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 nohup python hpo_grid_search.py \
  --base-config Config/ili.yaml \
  --train-npz Data/datasets/ili_delta/2017_18test_tau/tau03/ili_eng_2017_2018_T42_p14_train.npz \
  --val-npz   Data/datasets/ili_delta/2017_18test_tau/tau03/ili_eng_2017_2018_T42_p14_val.npz \
  --d-model 64 128 \
  --base-lr 1e-5 \
  --batch-size 64 128 \
  --max-epochs 18000 --save-cycle 1800 --val-num-repeats 1 \
  --gpu-slots "${GPU}:2" \
  --experiment-name eng_2017_2018_tau03_p14 \
  --output-root outputs/hpo/ili_delta/2017_18test_tau/tau03 \
  > "Logs/hpo/ili_delta/2017_18test_tau/tau03/eng_2017_2018_tau03_p14_${TS}.log" 2>&1 &
echo "[launched] eng_2017_2018_tau03_p14 on GPU ${GPU}  pid=$!  log=Logs/hpo/ili_delta/2017_18test_tau/tau03/eng_2017_2018_tau03_p14_${TS}.log"
